{{- if .Values.extensions.util.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-util
type: Opaque
stringData:
  azureClientSecretUtil: {{ .Values.extensions.util.azureClientSecretUtil }}
  azureClientIdUtil: {{ .Values.extensions.util.azureClientIdUtil }}
  azureTenantIdUtil: {{ .Values.extensions.util.azureTenantIdUtil }}
  azureKeyVaultUrlUtil: {{ .Values.extensions.util.azureKeyVaultUrlUtil }}
{{- end }}
