apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}
type: Opaque
stringData:
  sysadminPassword: {{ .Values.ckan.sysadminPassword }}
  smtpPassword: {{ .Values.ckan.smtp.password }}
  {{- if .Values.external.enabled }}
  psqlMasterPassword: {{ .Values.external.password }}
  psqlHost: {{ ternary "localhost" .Values.external.host (eq .Values.pgbouncer.enabled true)}}
  ckanSqlAlchemyUrl: "postgresql://{{ .Values.ckan.db.ckanDbUser }}:{{ .Values.ckan.db.ckanDbPassword  }}@{{ ternary "localhost" .Values.external.host (eq .Values.pgbouncer.enabled true)}}/{{ .Values.ckan.db.ckanDbName  }}"
  ckanDatastoreWriteUrl: "postgresql://{{ .Values.ckan.datastore.RwDbUser }}:{{ .Values.ckan.datastore.RwDbPassword }}@{{ ternary "localhost" .Values.external.host (eq .Values.pgbouncer.enabled true)}}/{{ .Values.ckan.datastore.RwDbName }}"
  ckanDatastoreReadUrl: "postgresql://{{ .Values.ckan.datastore.RoDbUser }}:{{ .Values.ckan.datastore.RoDbPassword }}@{{ ternary "localhost" .Values.external.host (eq .Values.pgbouncer.enabled true)}}/{{ .Values.ckan.datastore.RoDbName }}"
  {{- else if .Values.postgresql.enabled }}
  psqlMasterPassword: {{ .Values.postgresql.postgresqlPassword }}
  psqlHost: {{ ternary "localhost" (printf "%s-postgresql" .Release.Name) (eq .Values.pgbouncer.enabled true)}}
  ckanSqlAlchemyUrl: "postgresql://{{ .Values.ckan.db.ckanDbUser  }}:{{ .Values.ckan.db.ckanDbPassword  }}@{{ ternary "localhost" (printf "%s-postgresql" .Release.Name) (eq .Values.pgbouncer.enabled true)}}/{{ .Values.ckan.db.ckanDbName  }}"
  ckanDatastoreWriteUrl: "postgresql://{{ .Values.ckan.datastore.RwDbUser }}:{{ .Values.ckan.datastore.RwDbPassword }}@{{ ternary "localhost" (printf "%s-postgresql" .Release.Name) (eq .Values.pgbouncer.enabled true)}}/{{ .Values.ckan.datastore.RwDbName }}"
  ckanDatastoreReadUrl: "postgresql://{{ .Values.ckan.datastore.RoDbUser }}:{{ .Values.ckan.datastore.RoDbPassword }}@{{ ternary "localhost" (printf "%s-postgresql" .Release.Name) (eq .Values.pgbouncer.enabled true)}}/{{ .Values.ckan.datastore.RoDbName }}"
  {{- end }}
