{{- if .Values.extensions.util.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-util
type: Opaque
stringData:
  azureClientSecretUtil: {{ .Values.extensions.util.azureClientSecretUtil }}
{{- end }}
