apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "mutating-webhook.fullname" . }}-issuer
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "mutating-webhook.fullname" . }}-tls
  dnsNames:
  - {{ include "mutating-webhook.fullname" . }}
  - {{ include "mutating-webhook.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster
  - {{ include "mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }}
  isCA: false
  duration: {{ .Values.certificates.duration | default "720h0m0s" }}
  renewBefore: {{ .Values.certificates.renewBefore | default "120h0m0s" }}
  issuerRef:
    name: {{ include "mutating-webhook.fullname" . }}-issuer
    kind: Issuer
